FROM registry.access.redhat.com/ubi9/ubi-init
RUN yum update -y
RUN yum -y install git ruby ruby-devel rubygems gcc gcc-c++ make redhat-rpm-config httpd rubygem-rexml langpacks-en glibc-all-langpacks; yum clean all
RUN systemctl enable httpd
RUN gem install ascii_binder && yum clean all
RUN mkdir /etc/systemd/system/httpd.service.d/; echo -e '[Service]\nRestart=always' > /etc/systemd/system/httpd.service.d/httpd.conf
EXPOSE 80
ENV LANG=en_US.UTF-8
RUN touch index.html
RUN echo '<head><meta http-equiv="refresh" content="1; URL=./welcome/index.html" /></head><body><p>If you are not redirected in one second, <a href="./welcome/index.html">click here</a>.</p></body>' > index.html
RUN mv index.html /var/www/html/index.html

RUN git clone -b nokia-preview --single-branch https://github.com/aireilly/openshift-docs.git
RUN cd openshift-docs; asciibinder build -d openshift-webscale
RUN mv 'openshift-docs/_preview/openshift-enterprise/nokia-preview/'* /var/www/html
RUN rm -rf openshift-docs

CMD [ "/sbin/init" ]