FROM registry.access.redhat.com/ubi8/ubi-init
RUN yum update
RUN yum -y install git ruby ruby-devel rubygems gcc gcc-c++ make redhat-rpm-config httpd; yum clean all
RUN systemctl enable httpd
RUN gem install ascii_binder:1.0 yajl-ruby:1.4.1 && yum clean all
RUN mkdir /etc/systemd/system/httpd.service.d/; echo -e '[Service]\nRestart=always' > /etc/systemd/system/httpd.service.d/httpd.conf
EXPOSE 80

RUN git clone -b td-470 https://github.com/aireilly/openshift-docs.git
RUN cd /openshift-docs; asciibinder build
RUN touch index.html
RUN echo '<head><meta http-equiv="refresh" content="1; URL=./welcome/index.html" /></head><body><p>If you are not redirected in one second, <a href="./welcome/index.html">click here</a>.</p></body>' > index.html
RUN mv index.html /openshift-docs/_preview/openshift-enterprise/td-470/index.html
RUN mv '/openshift-docs/_preview/openshift-enterprise/td-470/'* /var/www/html
RUN rm -rf /openshift-docs

CMD [ "/sbin/init" ]